# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=3.2
group=me.daxanius.nmc
java_version=25

# Common
minecraft_version=26.1.2
mod_name=NoMiningCooldown
mod_author=Daxanius
mod_id=nmc
license=GPL-3.0
credits=
description=Fixes the client-side block breaking delay; this feature is toggleable with the key bound to "Toggle Mining Cooldown" under miscellaneous.
minecraft_version_range=[26.1.2,)

# Parchment is no longer needed as of 26.1 - Mojang removed obfuscation and ships real names
# parchment_minecraft=
# parchment_version=

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.151.0+26.1.2
fabric_loader_version=0.18.4

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge
forge_version=64.0.8
forge_loader_version_range=[64,)

# NeoForge
# https://neoforged.net/
neoforge_version=26.1.2.73
neoforge_loader_version_range=[11,)

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false