plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle'
}

jar {
    manifest {
        attributes([
            'MixinConfigs': 'nmc.mixins.json,nmc.forge.mixins.json'
        ])
    }
}

base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}

minecraft {
    mappings channel: 'official', version: minecraft_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer.from(at)
    }
    runs {
        client {
            workingDir = project.file('run')
        }
        server {
            workingDir = project.file('run')
        }
    }
}

repositories {
    maven(minecraft.getMavenizer())
    maven {
        name = 'Forge'
        url = 'https://maven.minecraftforge.net/'
    }
    maven {
        name = 'MC Libraries'
        url = 'https://libraries.minecraft.net/'
    }
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}
